
trigger: none
pool:
  vmImage: ubuntu-latest
steps:
- task: AzureCLI@2
  displayName: 'Create RG and deploy Bicep'
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az group create -n $(AZURE_RESOURCE_GROUP) -l $(AZURE_LOCATION)
      az deployment group create -g $(AZURE_RESOURCE_GROUP) -f infra/bicep/main.bicep -p namePrefix=rrm
